name: ZAP-Test

on:
  push: 
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python 3.7.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.7.8
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade zapcli
          apt-get install jq
      - name: Get working directory
        run: echo $(PWD)
      # - name: Get working directory
      #   run: apt-get install jq
      - name: Get ZAP Session
        run: |
          wget https://github.com/ni3galave/test-jekins/raw/master/zap-command-line-utitlity.zip
          unzip -o zap-command-line-utitlity.zip
          rm zap-command-line-utitlity.zip
          ls
          ls zap-command-line-utitlity/run-zap-scan.sh
          chmod +x zap-command-line-utitlity/run-zap-scan.sh
          echo $pwd
      - name: Install OWASP ZAP
        run: |
          mkdir -p ./zap
          cd ./zap
          wget -N https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
          tar -zxvf ZAP_2.9.0_Linux.tar.gz
          rm ZAP_2.9.0_Linux.tar.gz
          cd ZAP_2.9.0/plugin
          wget https://github.com/zaproxy/zap-extensions/releases/download/exportreport-v6/exportreport-alpha-6.zap
          echo 'export PATH_ZAP_SH=./zap/ZAP_2.9.0/zap.sh' >> ~/.bashrc
          echo 'export ZAP_PORT=8090' >> ~/.bashrc
          echo $pwd
      # - name: Run Docker Container
      #   run: docker run -d -p 5050:5050 vulnerable-app
      - name: Run ZAP Daemon
        run: ./zap/ZAP_2.9.0/zap.sh -daemon -port 8090 -config api.key=12345 -config api.disablekey=true-session ./zap/zap-command-line-utitlity/zap-session/PreProdSession.session > /dev/null &
      - name: Sleep for a bit
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      
      - name: Run Test Automation with ZAP
        run: ./zap-command-line-utitlity/run-zap-scan.sh
      - name: "Upload Report"
        uses: actions/upload-artifact@v1
        with:
          name: zap-scan-report
          path: ./zap-command-line-utitlity/report.html